project:
  type: website

website:
  title: "Teresa Bui"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About Me
      - href: projects.qmd
        text: Projects
      - href: work-experience.qmd
        text: Work Experience
        
  page-footer:
    right: "&copy; 2024, Teresa Bui"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
  

execute: 
  freeze: auto 


